# Generated by Django 6.0.3 on 2026-03-19 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0002_usuario_delete_pessoa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
